debug: true
servers:
  -
    name: "HSE"
    address: "imap.yandex.ru:993"
    username: "avdeviatkin@edu.hse.ru"
    password: "eeyruorerxofgbox"
  -
    name: "Ya"
    address: "imap.yandex.ru:993"
    username: "devyatkin.av@ya.ru"
    password: "qncmjdvpyoxefenw"
